### ISSUE TITLE
Pending Fixme

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-zcash-rs#7] opened 2020-12-04 21:32 UTC
https://github.com/Zondax/ledger-zcash-rs/blob/master/zcash-hsmbuilder/src/prover_ledger.rs#L154-L180

**Comment by leongb** [comment] 2020-12-07 07:55
This is a duplicate of https://github.com/Zondax/ledger-zcash-rs/issues/5

**Closed by leongb** 2020-12-07 07:55 UTC
